import type { Cell, LevelDefinition } from '../engine/types';

const cell = (x: number, y: number): Cell => ({ x, y });
const oneCell = [cell(0, 0)] as const;

/**
 * Each board isolates one rule or puzzle technique. They intentionally stay
 * small so a player can identify the relevant interaction at a glance.
 */
export const demoLevels: readonly LevelDefinition[] = [
  {
    id: 'push-01',
    title: '01 — 单次推送',
    description: '方块只会因一次输入平移一格；不能拉，也不能连推。',
    objective: '把 Block 推进地面 Goal。',
    hint: '连续向右两次。',
    mechanics: ['单次推送', '地面 Goal', '完成后下一关'],
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(3, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'push-block', position: cell(1, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'shape-02',
    title: '02 — 整体 footprint',
    description: '多格方块每次都作为一个整体平移；任意一格被 Wall 挡住，整体都不能动。',
    objective: '让竖向的两格 Block 同时覆盖两个地面 Goal。',
    hint: '向右推两次；右侧双格是多格 Wall。',
    mechanics: ['多格 footprint', '多格 Wall', '完整覆盖'],
    width: 5,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    dynamicWalls: [
      { id: 'shape-stop-wall', position: cell(4, 1), shape: [cell(0, 0), cell(0, 1)] },
    ],
    terrainGoals: [cell(3, 1), cell(3, 2)],
    terrainSpikes: [],
    blocks: [
      {
        id: 'domino-block',
        position: cell(1, 1),
        shape: [cell(0, 0), cell(0, 1)],
        number: 0,
        isFake: false,
      },
    ],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'match-03',
    title: '03 — 编号匹配',
    description: 'B2 是编号为 2 的方块；G2 是只接收编号为 2 的 Goal。',
    objective: '把 B2 推进 G2。',
    hint: 'B 与 G 的数字必须相同；向右两次。',
    mechanics: ['B2 / G2 编号', '动态 Goal'],
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [],
    terrainSpikes: [],
    blocks: [{ id: 'block-two', position: cell(1, 1), shape: oneCell, number: 2, isFake: false }],
    goals: [{ id: 'goal-two', position: cell(3, 1), shape: oneCell, number: 2, movable: false }],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'fake-04',
    title: '04 — Fake Block',
    description: 'Fake Block 仍会阻挡和移动，但它永远不计入通关条件；先让它移开，才能站到真实 Block 的推位。',
    objective: '把 Fake Block 移开，再把真实 Block 推进 Goal。',
    hint: '下、右、上、右。灰色 Fake Block 必须先让出白色 Block 左侧的推位。',
    mechanics: ['Fake Block', '不计入胜利', '让出推位'],
    width: 4,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(3, 1)],
    terrainSpikes: [],
    blocks: [
      { id: 'fake-block', position: cell(1, 1), shape: oneCell, number: 0, isFake: true },
      { id: 'fake-goal-block', position: cell(2, 1), shape: oneCell, number: 0, isFake: false },
    ],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'spike-05',
    title: '05 — 尖刺回位',
    description: '角色触碰 Spike 会触发死亡重置；Block、可推动 Goal 与 Gate 的任意格触碰 Spike，会在动作结束后的环境结算回到各自出生位置。',
    objective: '让 Block 先触碰 Spike 回位；此时角色会停在它的右侧，再把 Block 向左推入 Goal。',
    hint: '需要先连续把 Block 向右推两次，利用回位改变你与 Block 的相对位置。',
    mechanics: ['Spike', '对象回位', '尖刺重置'],
    width: 5,
    height: 1,
    weather: 'clear',
    player: cell(1, 0),
    walls: [],
    terrainGoals: [cell(0, 0)],
    terrainSpikes: [cell(4, 0)],
    blocks: [{ id: 'reset-block', position: cell(2, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'rain-06',
    title: '06 — 雨天滑行',
    description: '雨天只有角色滑行；相邻 Block 仍只会被推一格。',
    objective: '先滑到 Block 前，再把它推进地面 Goal。',
    hint: '先向右滑行，再向右推送。',
    mechanics: ['Rain', '滑行', '单格推送'],
    width: 5,
    height: 3,
    weather: 'rain',
    player: cell(0, 1),
    walls: [cell(4, 1)],
    terrainGoals: [cell(3, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'rain-block', position: cell(2, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'goal-07',
    title: '07 — 可推动 Goal',
    description: '可推动 Goal：能推就推；被 Block 挡住时，角色可以穿过它。',
    objective: '先推开可推动 Goal，再穿过它，把 B2 推进 G2。',
    hint: '向右四次；B2 只能放进 G2。',
    mechanics: ['可推动 Goal', '被阻挡时穿过', 'B2 / G2'],
    width: 6,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [],
    terrainSpikes: [],
    blocks: [{ id: 'goal-block-two', position: cell(3, 1), shape: oneCell, number: 2, isFake: false }],
    goals: [
      { id: 'mobile-goal', position: cell(1, 1), shape: oneCell, number: 0, movable: true },
      { id: 'number-two-goal', position: cell(5, 1), shape: oneCell, number: 2, movable: false },
    ],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'gate-08',
    title: '08 — Gate 传送',
    description: 'Gate 只传送角色：从入口进入后，会沿原输入方向从配对出口走出。',
    objective: '穿过 Gate，到 Block 右侧后向左推入 Goal。',
    hint: '右、下、左。',
    mechanics: ['Gate 传送', '方向保持'],
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0), cell(0, 2)],
    terrainGoals: [cell(2, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'gate-block', position: cell(3, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [
      { id: 'entry-gate', position: cell(1, 1), shape: oneCell, nextGateId: 'exit-gate' },
      { id: 'exit-gate', position: cell(3, 0), shape: oneCell, nextGateId: 'entry-gate' },
    ],
    spikes: [],
    paths: [],
  },
  {
    id: 'gate-push-09',
    title: '09 — Gate 可推',
    description: '若 Gate 的出口前方被挡住，入口 Gate 会变成可推动对象。',
    objective: '先推开入口 Gate，再进入下方通道推 Block。',
    hint: '右、下、右。',
    mechanics: ['出口阻挡', '可推动 Gate'],
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0), cell(0, 2), cell(4, 0)],
    terrainGoals: [cell(3, 2)],
    terrainSpikes: [],
    blocks: [{ id: 'gate-push-block', position: cell(2, 2), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [
      { id: 'blocked-entry-gate', position: cell(1, 1), shape: oneCell, nextGateId: 'blocked-exit-gate' },
      { id: 'blocked-exit-gate', position: cell(3, 0), shape: oneCell, nextGateId: 'blocked-entry-gate' },
    ],
    spikes: [],
    paths: [],
  },
  {
    id: 'path-loop-10',
    title: '10 — Loop Spike',
    description: '每次有效操作后，路径 Spike 沿 Loop 前进一个节点。',
    objective: '等 Spike 离开起点，再从它身后推 Block。',
    hint: '下、上、右、右。',
    mechanics: ['移动 Spike', 'Loop Path', '时机'],
    width: 4,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(3, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'loop-block', position: cell(2, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [{ id: 'loop-spike', position: cell(1, 1), shape: oneCell }],
    paths: [
      {
        id: 'loop-path',
        travelerId: 'loop-spike',
        nodes: [cell(1, 1), cell(1, 2), cell(2, 2), cell(2, 3), cell(1, 3)],
        loop: 'loop',
      },
    ],
  },
  {
    id: 'path-pingpong-11',
    title: '11 — Ping-pong Spike',
    description: 'Ping-pong Spike 不会被角色阻挡；一旦撞到角色，本关所有物品都会重置。',
    objective: '利用折返节奏绕开 Spike，在它离开左端后从上方推 Block。',
    hint: '上、下、右、下：先让 Spike 移到右端，再进入左端向下推 Block。',
    mechanics: ['移动 Spike', 'Ping-pong Path', '尖刺重置'],
    width: 4,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(1, 3)],
    terrainSpikes: [],
    blocks: [{ id: 'ping-block', position: cell(1, 2), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [{ id: 'ping-spike', position: cell(1, 1), shape: oneCell }],
    paths: [
      {
        id: 'ping-path',
        travelerId: 'ping-spike',
        nodes: [cell(1, 1), cell(2, 1), cell(3, 1)],
        loop: 'pingPong',
      },
    ],
  },
  {
    id: 'budget-12',
    title: '12 — 步数预算',
    description: '关卡可设定步数上限；达到上限时会在胜利判定前失败。',
    objective: '在三步以内把 Block 推进 Goal。',
    hint: '最短解是右、右；不要做无关移动。',
    mechanics: ['步数限制', '最短路径'],
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(3, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'budget-block', position: cell(1, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
    stepLimit: 3,
  },
];
