import type { LevelDefinition } from '../../engine/types';
import { cell, oneCell } from './shared';

export const gateLevels: readonly LevelDefinition[] = [
  {
    id: 'gate-guide-10',
    title: '10 — Gate 远端条件：先通过',
    description: '入口能否使用取决于出口沿入射方向的一格。出口可通时，Gate 是通道，不是可推动物。',
    objective: '从入口向右通过 Gate，到 Block 右侧后把它向左推入 Goal。',
    hint: '向右穿过 Gate；出口仍沿向右方向落脚，再向下、向左。',
    mechanics: ['Gate 远端条件', '出口可通时通过', '方向保持'],
    curriculum: {
      familyId: 'gate',
      familyTitle: 'Gate 远端条件',
      techniqueId: 'gate-remote-pushability',
      techniqueTitle: '出口决定入口行为',
      phase: 'guide',
    },
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0), cell(0, 2)],
    terrainGoals: [cell(2, 1)],
    terrainSpikes: [],
    blocks: [{ id: 'gate-guide-block', position: cell(3, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [
      { id: 'gate-guide-entry', position: cell(1, 1), shape: oneCell, nextGateId: 'gate-guide-exit' },
      { id: 'gate-guide-exit', position: cell(3, 0), shape: oneCell, nextGateId: 'gate-guide-entry' },
    ],
    spikes: [],
    paths: [],
  },
  {
    id: 'gate-verify-11',
    title: '11 — Gate 远端条件：出口受阻',
    description: '出口前方被 Wall 堵住时，角色不能通过；若入口前方有空间，同一次向右会把入口 Gate 推开。',
    objective: '利用出口受阻把入口 Gate 推开，再从下方把 Block 推进 Goal。',
    hint: '先向右：出口右侧的 Wall 让入口 Gate 变得可推；再下、右。',
    mechanics: ['Gate 远端条件', '出口受阻时可推', '入口落位'],
    curriculum: {
      familyId: 'gate',
      familyTitle: 'Gate 远端条件',
      techniqueId: 'gate-remote-pushability',
      techniqueTitle: '出口决定入口行为',
      phase: 'verify',
    },
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0), cell(0, 2), cell(4, 0)],
    terrainGoals: [cell(3, 2)],
    terrainSpikes: [],
    blocks: [{ id: 'gate-verify-block', position: cell(2, 2), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [
      { id: 'gate-verify-entry', position: cell(1, 1), shape: oneCell, nextGateId: 'gate-verify-exit' },
      { id: 'gate-verify-exit', position: cell(3, 0), shape: oneCell, nextGateId: 'gate-verify-entry' },
    ],
    spikes: [],
    paths: [],
  },
  {
    id: 'gate-challenge-12',
    title: '12 — Gate 远端条件：主动堵出口',
    description: '先通过 Gate 到右侧，把 Block 推到出口落点；返回后，原先的通道会因出口受阻变成可推动入口。',
    objective: '主动堵住出口，推开入口 Gate，再完成左侧 Block。',
    hint: '先穿门到右侧，从下方把右 Block 推上 Goal；再从出口向上返回，入口就能向右推开。',
    mechanics: ['Gate 远端条件', '主动堵出口', '通道变可推动物'],
    curriculum: {
      familyId: 'gate',
      familyTitle: 'Gate 远端条件',
      techniqueId: 'gate-remote-pushability',
      techniqueTitle: '出口决定入口行为',
      phase: 'challenge',
    },
    width: 7,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(3, 0), cell(3, 1), cell(3, 2), cell(3, 3)],
    terrainGoals: [cell(5, 1), cell(2, 2)],
    terrainSpikes: [],
    blocks: [
      { id: 'gate-challenge-exit-block', position: cell(5, 2), shape: oneCell, number: 0, isFake: false },
      { id: 'gate-challenge-left-block', position: cell(1, 2), shape: oneCell, number: 0, isFake: false },
    ],
    goals: [],
    gates: [
      { id: 'gate-challenge-entry', position: cell(1, 1), shape: oneCell, nextGateId: 'gate-challenge-exit' },
      { id: 'gate-challenge-exit', position: cell(4, 1), shape: oneCell, nextGateId: 'gate-challenge-entry' },
    ],
    spikes: [],
    paths: [],
  },
];
