import type { LevelDefinition } from '../../engine/types';
import { cell, oneCell } from './shared';

export const movableGoalLevels: readonly LevelDefinition[] = [
  {
    id: 'movable-goal-guide-07',
    title: '07 — 可推动 Goal：先推开',
    description: '前方有空位时，可推动 Goal 和 Block 一样会被推一格；先移动它，才能走到 Block 的推位。',
    objective: '推开 Goal，绕到上方，把 Block 推进 Terrain Goal。',
    hint: '先向右推 Goal；上去后再向右推 Block。',
    mechanics: ['可推动 Goal', 'Goal 也是物件', '腾出推位'],
    curriculum: {
      familyId: 'movable-goal',
      familyTitle: '可推动 Goal',
      techniqueId: 'goal-mode-switch',
      techniqueTitle: '推与穿的切换',
      phase: 'guide',
    },
    width: 4,
    height: 2,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0)],
    terrainGoals: [cell(3, 0)],
    terrainSpikes: [],
    blocks: [{ id: 'movable-goal-guide-block', position: cell(2, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [{ id: 'movable-goal-guide-goal', position: cell(1, 1), shape: oneCell, number: 0, movable: true }],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'movable-goal-verify-08',
    title: '08 — 可推动 Goal：推不动时穿过',
    description: '可推动 Goal 前方被 Block 堵住时，不会变成死路：角色会走到 Goal 上，再继续推 Block。',
    objective: '穿过被堵住的 Goal，把 Block 推进右侧 Terrain Goal。',
    hint: '第一下向右不是推 Goal，而是走到它上面；第二下才推 Block。',
    mechanics: ['可推动 Goal', '被堵后可穿过', '状态切换'],
    curriculum: {
      familyId: 'movable-goal',
      familyTitle: '可推动 Goal',
      techniqueId: 'goal-mode-switch',
      techniqueTitle: '推与穿的切换',
      phase: 'verify',
    },
    width: 4,
    height: 1,
    weather: 'clear',
    player: cell(0, 0),
    walls: [],
    terrainGoals: [cell(3, 0)],
    terrainSpikes: [],
    blocks: [{ id: 'movable-goal-verify-block', position: cell(2, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [{ id: 'movable-goal-verify-goal', position: cell(1, 0), shape: oneCell, number: 0, movable: true }],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'movable-goal-challenge-09',
    title: '09 — 可推动 Goal：推与穿的切换',
    description: '先把 Goal 推到 Block 前；它被 Block 堵住后变为可穿过的地面，角色才能从上方推 Block 进 Goal。',
    objective: '依次使用“推 Goal”与“穿过 Goal”，再把 Block 向下推入 Terrain Goal。',
    hint: '向右两次后，从上方绕到 Block；Goal 这时已不能继续向右推。',
    mechanics: ['可推动 Goal', '先推后穿', '状态切换'],
    curriculum: {
      familyId: 'movable-goal',
      familyTitle: '可推动 Goal',
      techniqueId: 'goal-mode-switch',
      techniqueTitle: '推与穿的切换',
      phase: 'challenge',
    },
    width: 5,
    height: 3,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(0, 0), cell(0, 2), cell(1, 2), cell(2, 2)],
    terrainGoals: [cell(3, 2)],
    terrainSpikes: [],
    blocks: [{ id: 'movable-goal-challenge-block', position: cell(3, 1), shape: oneCell, number: 0, isFake: false }],
    goals: [{ id: 'movable-goal-challenge-goal', position: cell(1, 1), shape: oneCell, number: 0, movable: true }],
    gates: [],
    spikes: [],
    paths: [],
  },
];
