import type { LevelDefinition } from '../../engine/types';
import { cell } from './shared';

export const occupancyLevels: readonly LevelDefinition[] = [
  {
    id: 'occupancy-guide-01',
    title: '01 — 整块占格：一起移动',
    description: '把多格 Block 当成一张不能旋转的沙发：移动时，它占住的每一格都会一起移动。',
    objective: '让竖向两格 Block 同时落在两个 Terrain Goal 上。',
    hint: '向右两次。两格会一起移动，也必须一起覆盖 Goal。',
    mechanics: ['整块占格', '一起移动', '完整目标覆盖'],
    curriculum: {
      familyId: 'occupancy',
      familyTitle: '整块占格',
      techniqueId: 'occupancy-clearance',
      techniqueTitle: '整块落位检查',
      phase: 'guide',
    },
    width: 5,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [],
    terrainGoals: [cell(3, 1), cell(3, 2)],
    terrainSpikes: [],
    blocks: [
      {
        id: 'occupancy-guide-domino',
        position: cell(1, 1),
        shape: [cell(0, 0), cell(0, 1)],
        number: 0,
        isFake: false,
      },
    ],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'occupancy-verify-02',
    title: '02 — 整块占格：一格受阻',
    description: '右边看似有空位，但竖向 Block 的下端会撞 Wall，所以整块不能向右。先换一条路径。',
    objective: '绕到 Block 下方，把它上移后再完整落到 Goal。',
    hint: '先下到底，再从下方向上推；最后从左侧向右停车。',
    mechanics: ['整块占格', '一格受阻，整块不动', '完整目标覆盖'],
    curriculum: {
      familyId: 'occupancy',
      familyTitle: '整块占格',
      techniqueId: 'occupancy-clearance',
      techniqueTitle: '整块落位检查',
      phase: 'verify',
    },
    width: 4,
    height: 4,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(2, 2)],
    terrainGoals: [cell(2, 0), cell(2, 1)],
    terrainSpikes: [],
    blocks: [
      {
        id: 'occupancy-verify-domino',
        position: cell(1, 1),
        shape: [cell(0, 0), cell(0, 1)],
        number: 0,
        isFake: false,
      },
    ],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'occupancy-challenge-03',
    title: '03 — 整块占格：绕开肩膀',
    description: 'L 形 Block 的右下“肩膀”会先撞上 Wall。先把整块降到下一排，再从左侧推入 L 形 Goal。',
    objective: '让 L 形 Block 的三格完整覆盖 L 形 Terrain Goal。',
    hint: '先向右一次；不要连续向右。绕到上方把它向下推，再回左侧完成停车。',
    mechanics: ['整块占格', 'L 形轮廓', '提前检查肩膀'],
    curriculum: {
      familyId: 'occupancy',
      familyTitle: '整块占格',
      techniqueId: 'occupancy-clearance',
      techniqueTitle: '整块落位检查',
      phase: 'challenge',
    },
    width: 5,
    height: 5,
    weather: 'clear',
    player: cell(0, 1),
    walls: [cell(4, 2)],
    terrainGoals: [cell(3, 2), cell(3, 3), cell(4, 3)],
    terrainSpikes: [],
    blocks: [
      {
        id: 'occupancy-challenge-l',
        position: cell(1, 1),
        shape: [cell(0, 0), cell(0, 1), cell(1, 1)],
        number: 0,
        isFake: false,
      },
    ],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
];
