import type { LevelDefinition } from '../../engine/types';
import { cell, oneCell } from './shared';

export const spikeResetLevels: readonly LevelDefinition[] = [
  {
    id: 'spike-guide-04',
    title: '04 — Spike 回位：穿过去',
    description: 'Block 可以被推入 Spike；它会回到出生点，但角色会留在 Spike 的另一侧。',
    objective: '先让 Block 回位，再从右侧把它推入左边的 Terrain Goal。',
    hint: '连续向右两次穿过 Spike；Block 回来后，再连续向左两次。',
    mechanics: ['Spike 回位', '物件回出生点', '改变站位'],
    curriculum: {
      familyId: 'spike-reset',
      familyTitle: 'Spike 回位',
      techniqueId: 'spike-reset-positioning',
      techniqueTitle: '用回位改变站位',
      phase: 'guide',
    },
    width: 5,
    height: 1,
    weather: 'clear',
    player: cell(1, 0),
    walls: [],
    terrainGoals: [cell(0, 0)],
    terrainSpikes: [cell(4, 0)],
    blocks: [{ id: 'spike-guide-block', position: cell(2, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'spike-verify-05',
    title: '05 — Spike 回位：换到另一侧',
    description: '从右侧把 Block 推入左边的 Spike，会把角色留在左侧；同一条回位规则可以反向使用。',
    objective: '先向左触发回位，再从左侧把 Block 推到右端 Goal。',
    hint: '向左两次后 Block 会回到中间；此时你已经在它左侧。',
    mechanics: ['Spike 回位', '回位方向', '改变站位'],
    curriculum: {
      familyId: 'spike-reset',
      familyTitle: 'Spike 回位',
      techniqueId: 'spike-reset-positioning',
      techniqueTitle: '用回位改变站位',
      phase: 'verify',
    },
    width: 6,
    height: 1,
    weather: 'clear',
    player: cell(4, 0),
    walls: [],
    terrainGoals: [cell(5, 0)],
    terrainSpikes: [cell(1, 0)],
    blocks: [{ id: 'spike-verify-block', position: cell(3, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
  {
    id: 'spike-challenge-06',
    title: '06 — Spike 回位：远端折返',
    description: 'Spike 离 Block 更远时，仍能用一次回位换边；难点是提前规划折返所需的整段推送。',
    objective: '把 Block 推到远端 Spike 回位，再从右侧折返推入左端 Goal。',
    hint: '先向右三次触发回位；回位后再向左三次。',
    mechanics: ['Spike 回位', '远端触发', '折返推送'],
    curriculum: {
      familyId: 'spike-reset',
      familyTitle: 'Spike 回位',
      techniqueId: 'spike-reset-positioning',
      techniqueTitle: '用回位改变站位',
      phase: 'challenge',
    },
    width: 6,
    height: 1,
    weather: 'clear',
    player: cell(1, 0),
    walls: [],
    terrainGoals: [cell(0, 0)],
    terrainSpikes: [cell(5, 0)],
    blocks: [{ id: 'spike-challenge-block', position: cell(2, 0), shape: oneCell, number: 0, isFake: false }],
    goals: [],
    gates: [],
    spikes: [],
    paths: [],
  },
];
